/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    Button: typeof import('primevue/button')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JsonChild1: typeof import('./src/components/JsonChild1.vue')['default']
    JsonChild2: typeof import('./src/components/JsonChild2.vue')['default']
    JsonData: typeof import('./src/components/JsonData.vue')['default']
    JsonDataChild: typeof import('./src/components/JsonDataChild.vue')['default']
    JsonDataParent: typeof import('./src/components/JsonDataParent.vue')['default']
    JsonParent: typeof import('./src/components/JsonParent.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
